import numpy as np
import pandas as pd
from scipy.stats import linregress
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import binom
from matplotlib.ticker import FuncFormatter
import statsmodels.api as sm
from amgm.utils import common
from statsmodels.graphics.tsaplots import plot_acf

def synthetic_NSDE_path(sample, synthetic_path, original_price, wdir, output_plot, font_size=12):  
    """
    Plots the synthetic path generated by the Neural SDE model along with the historical price window and Fibonacci levels.
    """
    
    hist = sample.price_window.detach().cpu().numpy()
    price_min = sample.sample_min.detach().cpu().numpy()
    price_range = sample.sample_range.detach().cpu().numpy()
    fib_levels = sample.fib_levels.detach().cpu().numpy()
    test_date = sample.test_dates
    issue_id = sample.issue_ids
    sample_output_plot = output_plot.with_name(f"{output_plot.stem}_{issue_id}_{test_date}.png")
    
    hist = hist * price_range + price_min  # Denormalize the historical window
    fib_levels = fib_levels * price_range + price_min  # Denormalize the Fibonacci levels
    
    hist_idx = np.arange(len(hist))
    fut_idx = np.arange(len(hist) - 1, len(hist) - 1 + len(synthetic_path))
    
    # One-column paper friendly size (~3.35in wide) with a less rectangular aspect.
    scale_factor = 2
    fig, ax = plt.subplots(figsize=(3.35 * scale_factor, 2.6 * scale_factor))
    ax.plot(hist_idx, hist, label="seed window", color="black", linewidth=2)
    ax.plot(fut_idx, synthetic_path, label="synthetic rollout", color="tab:blue", linewidth=2)
    ax.scatter([fut_idx[0]], [synthetic_path[0]], color="tab:red", zorder=5, label="SDE start")
    original_price = np.asarray(original_price)
    original_price_len = min(len(fut_idx), len(original_price))
    if original_price_len > 0:
        ax.plot(
            fut_idx[:original_price_len],
            original_price,
            label="original price",
            color="tab:green",
            linewidth=2,
        )
    x_min, x_max = 0, 352
    ax.set_xlim(x_min, x_max)
    ### Customize x-ticks to include the test date and avoid overlap
    current_ticks = ax.get_xticks()
    positive_ticks = current_ticks[current_ticks >= 0]
    if len(positive_ticks) > 1:
        tick_spacing = float(np.min(np.diff(positive_ticks)))
        min_distance_to_test_date = tick_spacing * 0.5
        filtered_ticks = positive_ticks[np.abs(positive_ticks - fut_idx[0]) > min_distance_to_test_date]
    else:
        filtered_ticks = positive_ticks
    custom_ticks = np.unique(np.append(filtered_ticks, fut_idx[0]))
    custom_ticks = custom_ticks[(custom_ticks >= x_min) & (custom_ticks <= x_max)]
    custom_labels = [str(test_date) if np.isclose(tick, fut_idx[0]) else f"{int(round(tick))}" for tick in custom_ticks]
    ax.set_xticks(custom_ticks)
    ax.set_xticklabels(custom_labels)
    ax.set_xlim(x_min, x_max)
    for tick, label in zip(custom_ticks, ax.get_xticklabels()):
        if np.isclose(tick, fut_idx[0]):
            label.set_rotation(45)
            label.set_horizontalalignment("right")
            label.set_color("red")
    ###        
    plot_fib_levels(fib_levels, ax)
    ax.set_xlabel("Step", fontsize=font_size)
    ax.set_ylabel("Price (USD)", fontsize=font_size)
    ax.set_title(f"Neural SDE synthetic rollout for {len(synthetic_path)-1} steps", fontsize=font_size)
    ax.legend(loc="best", fontsize=font_size)
    ax.tick_params(axis="both", labelsize=font_size)
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    fig.savefig(sample_output_plot, dpi=300)
    plt.close(fig)
    
def synthetic_NSDE_path_debug(sample, synthetic_path, original_price, wdir, output_plot, pi_path=None, mu_path=None, sigma_path=None):  
    """
    Plots the synthetic path generated by the Neural SDE model along with the historical price window and Fibonacci levels.
    """
    
    hist = sample.price_window.detach().cpu().numpy()
    price_min = sample.sample_min.detach().cpu().numpy()
    price_range = sample.sample_range.detach().cpu().numpy()
    fib_levels = sample.fib_levels.detach().cpu().numpy()
    test_date = sample.test_dates
    issue_id = sample.issue_ids
    sample_output_plot = output_plot.with_name(f"{output_plot.stem}_{issue_id}_{test_date}.png")
    avg_abs_diff = np.mean(np.abs(hist[1:] - hist[:-1]))
    hist = hist * price_range + price_min  # Denormalize the historical window
    fib_levels = fib_levels * price_range + price_min  # Denormalize the Fibonacci levels
    
    
    hist_idx = np.arange(len(hist))
    fut_idx = np.arange(len(hist) - 1, len(hist) - 1 + len(synthetic_path))
    
    fig, axes = plt.subplots(
        4,
        1,
        figsize=(12, 10),
        sharex=True,
        gridspec_kw={"height_ratios": [3, 1.3, 1.2, 1.2]},
    )
    ax = axes[0]
    ax.plot(hist_idx, hist, label="seed window", color="black", linewidth=2)
    ax.plot(fut_idx, synthetic_path, label="synthetic rollout", color="tab:blue", linewidth=2)
    ax.scatter([fut_idx[0]], [synthetic_path[0]], color="tab:red", zorder=5, label="SDE start")
    original_price = np.asarray(original_price)
    original_price_len = min(len(fut_idx), len(original_price))
    if original_price_len > 0:
        ax.plot(
            fut_idx[:original_price_len],
            original_price,
            label="original price",
            color="tab:green",
            linewidth=2,
        )
    ax.set_xlim(left=0)
    # Plot rollout statistics only on future steps where model outputs are defined.
    fut_stats_idx = fut_idx[1:]
    has_stats = (pi_path is not None) and (mu_path is not None) and (sigma_path is not None)
    pi_vals = None
    mu_vals = None
    sigma_vals = None
    if has_stats:
        pi_vals = np.asarray(pi_path)
        mu_vals = np.asarray(mu_path).reshape(-1)
        sigma_vals = np.asarray(sigma_path).reshape(-1)

        if pi_vals.ndim == 1:
            pi_vals = pi_vals.reshape(-1, 1)
        common_len = min(len(fut_stats_idx), len(mu_vals), len(sigma_vals), pi_vals.shape[0])
    else:
        common_len = 0
    if common_len > 0 and pi_vals is not None and mu_vals is not None and sigma_vals is not None:
        fut_stats_idx = fut_stats_idx[:common_len]
        mu_vals = mu_vals[:common_len]
        sigma_vals = sigma_vals[:common_len]
        pi_vals = pi_vals[:common_len]

        pi_ax = axes[1]
        class_colors = ["tab:blue", "tab:orange", "tab:green"]
        for class_idx in range(pi_vals.shape[1]):
            color = class_colors[class_idx % len(class_colors)]
            pi_ax.plot(
                fut_stats_idx,
                pi_vals[:, class_idx],
                linewidth=1.5,
                color=color,
                label=f"pi[{class_idx}]",
            )
        pi_ax.set_ylabel("pi")
        pi_ax.set_ylim(-0.05, 1.05)
        pi_ax.grid(True, alpha=0.3)
        pi_ax.legend(loc="best", ncol=min(3, pi_vals.shape[1]), fontsize=8)

        mu_ax = axes[2]
        mu_ax.plot(fut_stats_idx, mu_vals, color="tab:purple", linewidth=1.5, label="mu")
        mu_ax.set_ylabel("mu")
        mu_ax.grid(True, alpha=0.3)
        mu_ax.legend(loc="best", fontsize=8)

        sigma_ax = axes[3]
        sigma_ax.plot(fut_stats_idx, sigma_vals, color="tab:brown", linewidth=1.5, label="sigma")
        sigma_ax.set_ylabel("sigma")
        sigma_ax.set_xlabel("Step")
        sigma_ax.grid(True, alpha=0.3)
        sigma_ax.legend(loc="best", fontsize=8)
    else:
        for aux_ax, name in zip(axes[1:], ["pi", "mu", "sigma"]):
            aux_ax.text(0.5, 0.5, f"No {name} values to plot", ha="center", va="center", transform=aux_ax.transAxes)
            aux_ax.set_ylabel(name)
            aux_ax.grid(True, alpha=0.3)
        axes[-1].set_xlabel("Step")

    ### Customize x-ticks to include the test date and avoid overlap
    current_ticks = ax.get_xticks()
    positive_ticks = current_ticks[current_ticks >= 0]
    if len(positive_ticks) > 1:
        tick_spacing = float(np.min(np.diff(positive_ticks)))
        min_distance_to_test_date = tick_spacing * 0.5
        filtered_ticks = positive_ticks[np.abs(positive_ticks - fut_idx[0]) > min_distance_to_test_date]
    else:
        filtered_ticks = positive_ticks
    custom_ticks = np.unique(np.append(filtered_ticks, fut_idx[0]))
    custom_labels = [str(test_date) if np.isclose(tick, fut_idx[0]) else f"{int(round(tick))}" for tick in custom_ticks]
    axes[-1].set_xticks(custom_ticks)
    axes[-1].set_xticklabels(custom_labels)
    for tick, label in zip(custom_ticks, axes[-1].get_xticklabels()):
        if np.isclose(tick, fut_idx[0]):
            label.set_rotation(45)
            label.set_horizontalalignment("right")
            label.set_color("red")
    ###        
    plot_fib_levels(fib_levels, ax)
    ax.set_ylabel("Price")
    ax.set_title(f"Neural SDE synthetic rollout, Issue_id: {issue_id}, Avg dx: {avg_abs_diff:.4f}")
    ax.legend(loc="best")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    fig.savefig(sample_output_plot, dpi=150)
    plt.close(fig)

def price_window_and_fib_levels(x_window, fib_levels, features, wdir, x_t, x_tp1, x_tp1_pred, file_name="price_window_and_fib_levels.png"):
    """
    Plots the price window and Fibonacci levels, along with the current price, next price, and predicted next price.
    """
    fib_names = ["0.0","0.23", "0.38", "0.5", "0.61", "0.78","1.0"]  # adjust to your levels
    feature_values = np.asarray(features).reshape(-1)

    fig, ax = plt.subplots(figsize=(10, 6))

    ax.plot(x_window, label="x_window", color="black", linewidth=2)
    plot_fib_levels(fib_levels, ax)

    feature_lines = ["Features"]
    for name, value in zip(fib_names, feature_values):
        feature_lines.append(f"{name}: {value:.4f}")

    ax.text(
        0.02,
        0.98,
        "\n".join(feature_lines),
        transform=ax.transAxes,
        va="top",
        ha="left",
        fontsize=8,
        family="monospace",
        bbox=dict(
            boxstyle="round,pad=0.35",
            facecolor="white",
            edgecolor="gray",
            alpha=0.85,
        ),
    )

    ax.set_title(
        f'x_t: {x_t:.4f}, '
        f'x_tp1: {x_tp1:.4f}, '
        f'x_tp1_pred: {x_tp1_pred:.4f}'
    )
    ax.set_xlabel("Time Step")
    ax.set_ylabel("Price")
    ax.legend(loc="best")
    fig.tight_layout()
    fig.savefig(wdir / file_name, dpi=150)

def plot_fib_levels(fib_levels, ax):
    """ 
    Plots Fibonacci levels on the given axis with labels and colors. 
    """
    fib_names = ["0.0","0.23", "0.38", "0.5", "0.61", "0.78","1.0"]  # adjust to your levels
    colors = plt.cm.tab10.colors
    for i, level in enumerate(fib_levels):
        color = colors[i % len(colors)]
        name = fib_names[i] if i < len(fib_names) else f"fib_{i}"

        ax.axhline(y=level, color=color, linestyle="--", linewidth=1.5)
        ax.text(
            1.01, level, name,
            transform=ax.get_yaxis_transform(),
            color=color,
            va="center",
            ha="left",
            fontsize=9,
            bbox=dict(facecolor="white", alpha=0.75, edgecolor="none", pad=1.5),
        )
            
def regression_residual_performance(y_true, y_hat, wdir, 
                                    bin_names=None, mean_MAE=None, std_MAE=None, 
                                    dataset_type=None, 
                                    model="daily_378_63_US_Stocks", 
                                    output_range=50):
    """
    Plots the regression residual performance with two subplots:
    1. Mean Absolute Error (MAE) per bin
    2. Scatter plot of predictions vs true labels with mean and std error bars for each bin.
    
    Parameters:
    y_true (np.ndarray): True labels.
    y_hat (np.ndarray): Predicted labels.
    wdir (Path): Directory to save the plots.
    bin_names (list of str): ['gt20', '15to20', '10to15', '5to10', '0to5', 'zero', 'n0to4', 'n4to8', 'n8to12', 'n12to15', 'lt15']
    mean_MAE (array-like): Mean MAE for each bin.
    std_MAE (array-like): Standard deviation of MAE for each bin.
    dataset_type (str): Type of dataset, either "train" or "validation".
    model (str): Model identifier, e.g., "daily_378_63".
    output_range (int): Range of output values for the max residual.
    """

    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    # Set a common title for the entire figure
    fig.suptitle("Regression Residual Performance, labels: max residual percentages during lookforward period", fontsize=16, fontweight='bold')
    # Subplot 1: MAE per bin
    axes[0].errorbar(bin_names, mean_MAE, yerr=std_MAE, fmt='-o', ecolor='r', capsize=5, label='MAE ± Std')
    axes[0].set_xlabel('Max Residual Bin (%)')
    axes[0].set_ylabel('Mean Absolute Error (%)')
    axes[0].set_title("Average MAE of maximum residual percentages vs Bins")
    axes[0].legend()
    axes[0].grid(True)
    
    # Subplot 2: prediction vs label scatter
    axes[1].scatter(y_true, y_hat, alpha=0.2, s=5, label='Predictions')
    axes[1].plot([-output_range, output_range], [-output_range, output_range], 'r--', label='Ideal: y_hat = y_true')
    axes[1].set_xlabel('Label')
    axes[1].set_ylabel('Prediction')
    axes[1].set_title("Predictions vs True Labels")
    axes[1].legend()
    axes[1].grid(True)
    
    plt.tight_layout()
    if wdir is not None:
        file_name = f"regression_residual_{model}_{dataset_type}.png" if dataset_type is not None else f"regression_residual_{model}.png"
        plt.savefig(wdir / file_name)
        plt.close()
    else:
        return fig


def regression_residual_MAE_per_bin(mean_MAE, std_MAE, wdir, bin_names, model="daily_378_63"):
    """
    Plots the mean and standard deviation of MAE for each bin.
    
    Parameters:
    mean_MAE (array-like): Mean MAE for each bin.
    std_MAE (array-like): Standard deviation of MAE for each bin.
    wdir (Path): Directory to save the plot.
    bin_names (list of str): ['gt20', '15to20', '10to15', '5to10', '0to5', 'zero', 'n0to4', 'n4to8', 'n8to12', 'n12to15', 'lt15']
    """
    
    plt.figure(figsize=(10, 6))
    plt.errorbar(bin_names, mean_MAE, yerr=std_MAE, fmt='-o', ecolor='r', capsize=5)
    plt.title("Average MAE of maximum residual percentages vs Bins")
    plt.xlabel("Max Residual Bin (%)")
    plt.ylabel("Mean Absolute Error (%)")
    plt.grid()
    plt.savefig(wdir / f"MAE_vs_bins_residual_{model}.png")
    plt.close()

def regression_time_MAE_per_label(mean_MAE, std_MAE, wdir, model="daily_378_63"):
    """
    Plots the mean and standard deviation of MAE for each label.
    
    Parameters:
    mean_MAE (array-like): Mean MAE for each label.
    std_MAE (array-like): Standard deviation of MAE for each label.
    wdir (Path): Directory to save the plot.
    model (str): Model identifier, e.g., "daily_378_63".
    """
    labels = np.arange(-63, 64)  # Assuming labels are from -63 to 63
    plt.figure(figsize=(10, 6))
    plt.errorbar(labels, mean_MAE, yerr=std_MAE, fmt='-o', ecolor='r', capsize=5)
    plt.title("Ensemble MAE vs labels")
    plt.xlabel("Label")
    plt.ylabel("Mean Absolute Error (days)")
    plt.grid()
    plt.savefig(wdir / f"MAE_vs_labels_time_{model}.png")
    plt.close()

def regression_time_performance(y_true, y_hat, wdir, mean_MAE=None, std_MAE=None, model="daily_378_63_US_Stocks"):
    """
    Plots the regression performance with two subplots:
    1. Mean Absolute Error (MAE) per label
    2. Scatter plot of predictions vs true labels with mean and std error bars for each label.
    
    Parameters:
    y_true (np.ndarray): True labels.
    y_hat (np.ndarray): Predicted labels.
    mean_MAE (array-like): Mean MAE for each label.
    std_MAE (array-like): Standard deviation of MAE for each label.
    wdir (Path): Directory to save the plots.
    model (str): Model name for the plot title.
    """
    w_tst = int(model.split("_")[2])  # Extract window_size_test from model name, e.g., "daily_378_63_US_Stocks" -> "63"
    unique_classes, counts = np.unique(y_true, return_counts=True)

    if mean_MAE is None or std_MAE is None:
        # Compute mean absolute error for each label
        errors = y_true - y_hat
        mean_MAE = [np.abs(errors[y_true == label]).mean() for label in unique_classes]
    
    mean_y_hat_per_label = [y_hat[y_true == label].mean() for label in unique_classes]
    std_y_hat_per_label = [y_hat[y_true == label].std() for label in unique_classes]

    
    fig, axes = plt.subplots(1, 2, figsize=(16, 6))
    # Set a common title for the entire figure
    fig.suptitle("Regression time Performance, labels: days counting from the end of the lookforward window", fontsize=16, fontweight='bold')
    # Subplot 1: MAE per label
    if mean_MAE is not None and std_MAE is not None:
        axes[0].errorbar(unique_classes, mean_MAE, yerr=std_MAE, fmt='-o', ecolor='r', capsize=5, label='MAE ± Std')
    else:
        axes[0].plot(unique_classes, mean_MAE, '-o', label= 'MAE')
    axes[0].set_xlim(-w_tst-1, w_tst+1)
    axes[0].set_xlabel('Label')
    axes[0].set_ylabel('Mean Absolute Error (days)')
    axes[0].set_title('MAE per Label')
    axes[0].legend()
    axes[0].grid(True)

    # Subplot 2: prediction vs label scatter
    axes[1].scatter(y_true, y_hat, alpha=0.2, s=5, label='Predictions')
    axes[1].plot([-w_tst, w_tst], [-w_tst, w_tst], 'r--', label='Ideal: y_hat = y_true')
    axes[1].errorbar(unique_classes, mean_y_hat_per_label, yerr=std_y_hat_per_label, fmt='o', color='green', label='Mean ± Std of Predictions')    
    axes[1].set_xlim(-w_tst-1, w_tst+1)
    axes[1].set_xlabel('Label')
    axes[1].set_ylabel('Prediction')
    axes[1].set_title('Validation Predictions vs Labels')
    axes[1].legend()
    axes[1].grid(True)

    plt.tight_layout()
    if wdir is not None:
        plt.savefig(wdir / f"regression_time_{model}.png", dpi=150, bbox_inches='tight')
        plt.close()
    else:
        return fig
    

def linear_trend_plot(stock_price, date_window, test_date, y_hat, y_true, 
                      issue_id, wdir, time_bar, window_size_train=378, window_size_test=63, plot_log_scale=False, 
                      y_hat_reg_time=None, y_hat_reg_residual=None):
    """
    Docstring for linear_trend_plot
    
    Parameters:
    -----------
    y_hat_reg_time : float, shape: (1,10), optional
        Regression prediction for days from the end of the window.
        Positive values indicate upper boundary, negative for lower boundary.
    y_hat_reg_residual : float, shape (1,10), optional
        Percentage deviation above/below the 95% CI borders (in percentage form, e.g., 5 for 5%).
        Positive values plot above upper border, negative below lower border. Zero means inside the CI.
        
    """
    import pandas as pd
    
    class_labels = ['Down', 'NoTouch', 'Up'] 
    x_values = np.arange(len(stock_price))
    x_total = np.arange(window_size_train + window_size_test)
    
    # Use date_window for the date range, aligned with stock_price.
    # Supplement with pandas BDay only if date_window is shorter than needed.
    
    # Convert date_window to pandas DatetimeIndex (handles numpy arrays and string conversion)
    date_window_flat = date_window.flatten() if hasattr(date_window, 'flatten') else date_window
    # Unwrap single-element tuples produced by PyTorch DataLoader collation (batch_size=1 transposes [B,T] -> [T,B])
    if isinstance(date_window_flat, (list, tuple)) and len(date_window_flat) > 0 and isinstance(date_window_flat[0], tuple):
        date_window_flat = [item[0] for item in date_window_flat]
    date_window_dt = pd.to_datetime(date_window_flat)
    
    total_window = window_size_train + window_size_test
    if len(date_window_dt) == total_window:
        date_range = date_window_dt[:total_window]
        
    elif len(date_window_dt) < total_window:
        dates_from_window = date_window_dt[:window_size_train]
        last_date = dates_from_window[-1]
        dates_after = pd.bdate_range(start=last_date, periods=window_size_test + 1)[1:]
        date_range = dates_from_window.append(dates_after)
    
    # Optimize figure size and DPI for faster rendering
    fig, ax = plt.subplots(figsize=(8, 3), dpi=100)  # Reduced from (10,4) at dpi=300
    ax.plot(x_values, stock_price, color='blue', linewidth=1.5, label='Stock Price')  # Reduced linewidth
    y_residual_lower_min = highlight_ci(x_total, stock_price, window_size_train, window_size_test, time_bar, color='orange', y_hat_reg_time=y_hat_reg_time, y_hat_reg_residual=y_hat_reg_residual)
    ax.axvline(x=window_size_train-1, color='red', linestyle='--', linewidth=1.5, label='Test Date')  # Reduced linewidth
    
    # Set x-axis ticks to show dates
    total_window = window_size_train + window_size_test
    if total_window == 26:
        # Show every 5th dates excluding the last date
        ticks = np.array([0, 5, 10, 15, 25])  # Fixed ticks for 26-day window
    else:
        step = max(1, len(date_range) // 5)  # Show approximately 5 date labels
        ticks = np.arange(0, len(date_range), step)
        # Ensure the last date is always included
        if len(date_range) - 1 not in ticks:
            ticks = np.append(ticks, len(date_range) - 1)
    ax.set_xticks(ticks)
    ax.set_xticklabels([d.strftime('%Y-%m-%d') for d in date_range[ticks]], rotation=45, ha='right', fontsize=7)
    
    if plot_log_scale:
        ax.set_yscale('log')
        # Set y-axis limit to ensure visibility of residuals, but not too high to distort the plot
        min_price = stock_price.min().item() if hasattr(stock_price.min(), 'item') else float(stock_price.min())
        min_y_lim = min(y_residual_lower_min, 0.8 * min_price)  # Ensure we don't set y-limit too high
        ax.set_ylim(bottom=min_y_lim)
        
    # Add date annotation below the vertical line
    y_min = ax.get_ylim()[0]
    ax.text(window_size_train-1, y_min, f'{test_date}', 
            rotation=45, ha='right', va='top', fontsize=9, color='red')
    
    label_str = 'NA' if y_true == -1 else class_labels[y_true]
    ax.set_title(f'Issue ID: {issue_id}, Label={label_str}, Predicted={class_labels[y_hat]}', fontsize=11)
    
    # Dynamically choose legend location (left corners only) based on data distribution
    y_min, y_max = ax.get_ylim()
    y_mid = (y_min + y_max) / 2
    # Check the mean of the first 20% of data points
    first_20_pct = stock_price[:int(len(stock_price) * 0.2)]
    first_mean = first_20_pct.mean()
    legend_loc = 'lower left' if first_mean > y_mid else 'upper left'
    
    ax.legend(loc=legend_loc, fontsize=6)
    ax.set_xlabel("Date", fontsize=9)
    ax.set_ylabel("Price (USD)", fontsize=9)
    
    ax.grid(alpha=0.3)  # Lighter grid for reduced file size
    # Create directory if it doesn't exist
    (wdir / f"Misclassified_samples_{time_bar}_issueID_{issue_id}").mkdir(parents=True, exist_ok=True)
    # Save the plot with compression optimization
    fig.savefig(wdir / f"Misclassified_samples_{time_bar}_issueID_{issue_id}" / f"misclassified_issueID_{issue_id}_{test_date}.png", 
                dpi=100, bbox_inches='tight', pad_inches=0.05, facecolor='white')
    # Return the figure for Streamlit
    return fig
  

def highlight_ci(x_index, y, window_size_train, window_size_test, time_bar, color, y_hat_reg_time=None, y_hat_reg_residual=None):
    """
    Highlights the 95% confidence interval of a linear regression model on a plot.
    Additionally highlights the regression-predicted border region if y_hat_reg_time is provided.
    
    Parameters:
    -----------
    x_index : array-like
        X-axis indices for plotting
    y : array-like
        Y-axis values (price data)
    window_size_train : int
        Size of training window
    window_size_test : int
        Size of test window
    time_bar : str
        Time frequency ('daily', 'weekly', or 'monthly')
    color : str
        Color for main CI highlight
    y_hat_reg_time : float, optional
        Regression prediction for days from the end of the window.
        Positive values indicate upper boundary, negative for lower boundary.
    y_hat_reg_residual : float, shape: (1,10), optional
        Percentage deviation above/below the 95% CI borders (in percentage form, e.g., 5 for 5%).
        Positive values plot above upper border, negative below lower border. Zero means inside the CI.
    Example usage:
        plt.figure(figsize=(10, 6))
        plt.plot(x_252, x_val_252[row, :], linewidth=2, label='252-day Model', color='blue')
        highlight_ci(x_252, y, color='blue', y_hat_reg_time=y_hat_reg_time)
        plt.grid()
    """
    # Fit linear model
    # Assuming y is a PyTorch tensor of shape [252, 1]
    y = y.squeeze().numpy()  # Convert to NumPy array and remove extra dimension
    x = np.arange(len(y))
    y_train = y[:window_size_train]
    x_train = x[:window_size_train]
    # Resample to the time bar frequency
    d = dict(daily=1, weekly=5, monthly=21)[time_bar]
    y_downsampled = y_train[::d]
    x_downsampled = x_train[::d]
    slope, intercept = common.fast_linreg_numba(x_downsampled, y_downsampled)
    y_pred = intercept + slope * x_train
    residuals = y_train - y_pred
    ci = 1.96 * np.std(residuals)
    
    y_linear = intercept + slope * x_index
    y_lower_border = y_linear - ci
    y_upper_border = y_linear + ci
  
    plt.plot(x_index, y_linear, color=color, linestyle='-', linewidth=2, label='Linear Fit')
    # Plot confidence interval
    plt.fill_between(x_index, y_lower_border, y_upper_border, color=color, alpha=0.2, label='95% CI')
    
    # Plot ensemble model predictions as markers if y_hat_reg_time is provided
    if y_hat_reg_time is not None:
        # Convert to numpy if it's a tensor
        y_hat_reg_time = y_hat_reg_time.cpu().numpy()
        y_hat_reg_time = np.asarray(y_hat_reg_time).flatten()  # Flatten to 1D array
        
        x_end = x_index[-1]  # Last index (end of window)
        
        # Plot a marker for each ensemble prediction
        for i, y_hat_reg in enumerate(y_hat_reg_time):
            y_hat_reg = float(y_hat_reg)
            
            # Calculate x-position: x_end - |days_from_end|
            x_marker = x_end - abs(y_hat_reg)
            
            if y_hat_reg >= 1:
                # Positive: marker on UPPER boundary (y_linear + ci)
                y_marker = np.interp(x_marker, x_index, y_upper_border)
                plt.plot(x_marker, y_marker, marker='o', linestyle='none', markersize=6, color='green', 
                        markeredgecolor='darkgreen', markeredgewidth=1, zorder=11, 
                        label='Touch Prediction' if i == 0 else None)
            elif y_hat_reg <= -1:
                # Negative: marker on LOWER boundary (y_linear - ci)
                y_marker = np.interp(x_marker, x_index, y_lower_border)
                plt.plot(x_marker, y_marker, marker='o', linestyle='none', markersize=6, color='red', 
                        markeredgecolor='darkred', markeredgewidth=1, zorder=11,
                        label='Touch Prediction' if i == 0 else None)
            else:
                # Values between -1 and +1: interpolate y_marker between lower and upper CI at x_end
                x_marker = x_end  # Marker at the end of the window
                y_marker = np.interp(y_hat_reg, [-1, 1], [y_lower_border[-1], y_upper_border[-1]])
                plt.plot(x_marker, y_marker, marker='o', linestyle='none', markersize=6, color='blue', 
                        markeredgecolor='darkblue', markeredgewidth=1, zorder=11,
                        label='Touch Prediction' if i == 0 else None)
              
    # Plot residual borders if y_hat_reg_residual is provided
    if y_hat_reg_residual is not None:
        # Convert to numpy if it's a tensor
        # Flatten to 1D array
        y_hat_reg_residual = np.asarray(y_hat_reg_residual).flatten()
        
        # Get indices for last window_size_test days
        x_residual = x_index[-window_size_test-1:]
        y_lower_border_test = y_lower_border[-window_size_test-1:]
        y_upper_border_test = y_upper_border[-window_size_test-1:]
        
        # Filter out zero values for statistics
        non_zero_residuals = y_hat_reg_residual[y_hat_reg_residual != 0]
        
        if len(non_zero_residuals) > 0:
            # Calculate statistics
            residual_mean = np.mean(non_zero_residuals)
            residual_std = np.std(non_zero_residuals)
            
            # Calculate mean+std and mean-std
            mean_plus_std = float(residual_mean + residual_std)
            mean_minus_std = float(residual_mean - residual_std)
            residual_mean = float(residual_mean)
            
            print(f"Residual Mean: {residual_mean:.2f}%, Residual Std: {residual_std:.2f}%, Mean+Std: {mean_plus_std:.2f}%, Mean-Std: {mean_minus_std:.2f}%")
            print(f"y_hat_reg_residual: {y_hat_reg_residual}")
            # Calculate borders for mean
            if residual_mean >= 0:
                y_residual_mean = y_upper_border_test * (1 + residual_mean / 100)
                color_mean = 'green'
            else:
                y_residual_mean = y_lower_border_test * (1 + residual_mean / 100)
                color_mean = 'red'
            
            # Plot mean line
            plt.plot(x_residual, y_residual_mean, color=color_mean, linestyle='-', linewidth=2, alpha=0.8,
                    label='Residual Prediction Mean')
            
            # Calculate and highlight borders for mean+std
            if mean_plus_std > 0 and mean_minus_std > 0:
                y_residual_upper = y_upper_border_test * (1 + mean_plus_std / 100)
                y_residual_lower = y_upper_border_test * (1 + mean_minus_std / 100)
                plt.fill_between(x_residual, y_residual_lower, y_residual_upper, 
                                color='green', alpha=0.2, label='Uncertainty Range ($\pm$std)')
            elif mean_plus_std >= 0 and mean_minus_std <= 0:
                y_residual_upper = y_upper_border_test * (1 + mean_plus_std / 100)
                y_residual_lower = y_lower_border_test * (1 + mean_minus_std / 100)
                plt.fill_between(x_residual, y_upper_border_test, y_residual_upper, 
                                color='green', alpha=0.2, label='Uncertainty Range ($+$std)')
                plt.fill_between(x_residual, y_residual_lower, y_lower_border_test,
                                color='red', alpha=0.2, label='Uncertainty Range ($-$std)')
            elif mean_plus_std < 0 and mean_minus_std < 0:
                y_residual_upper = y_lower_border_test * (1 + mean_plus_std / 100)
                y_residual_lower = y_lower_border_test * (1 + mean_minus_std / 100)
                plt.fill_between(x_residual, y_residual_lower, y_residual_upper, 
                                color='red', alpha=0.2, label='Uncertainty Range ($\pm$std)')
        
        # Annotate the mean value at x_index[-t_ind]
        t_ind = 1
        x_text = x_index[-t_ind]
        
        # Calculate y position for mean
        if residual_mean >= 0:
            y_border_mean = y_upper_border_test * (1 + residual_mean / 100)
            y_text_mean = y_border_mean[-t_ind]
            plt.text(x_text, y_text_mean, f"{residual_mean:.1f}%", color='green', va='top', ha='left', fontsize=9)
        else:
            y_border_mean = y_lower_border_test * (1 + residual_mean / 100)
            y_text_mean = y_border_mean[-t_ind]
            plt.text(x_text, y_text_mean, f"{residual_mean:.1f}%", color='red', va='top', ha='left', fontsize=9)
    
    # Annotate the upper and lower CI at the last x value
    x_last = x_index[-1]
    y_lower = round(y_linear[-1] - ci, 1)
    y_upper = round(y_linear[-1] + ci, 1)
    plt.text(x_last, y_lower, f"{y_lower}", color='orange', va='bottom', ha='left', fontsize=9)
    plt.text(x_last, y_upper, f"{y_upper}", color='orange', va='top', ha='left', fontsize=9)
    
    # Return minimum of y_lower_border for conditional y-limit setting
    return np.min(y_residual_lower)
    
    
def predictions_over_time(stock_price, y_hat, y_true, p_hat, test_date_list, issue_id, wdir, lookback, time_bar, prediction_difficulty_scores=None):
    """ Plots stock price, predictions, and labels over time for a single issueID.
    
    Parameters:
    -----------
    stock_price : array-like, shape (N,)
        Stock prices over time
    y_hat : array-like, shape (N,)
        Predicted class labels
    y_true : array-like, shape (N,)
        True class labels
    p_hat : array-like, shape (N, 3)
        Predicted probabilities for 3 classes
    test_date_list : list
        List of dates corresponding to predictions
    issue_id : str/int
        Stock identifier
    wdir : Path
        Working directory to save the plot
    lookback : int
        Lookback window size (for filename)
    prediction_difficulty_scores : array-like, shape (N,), optional
        Prediction difficulty scores for each prediction
    """
    # Convert to numpy if needed
    if hasattr(stock_price, 'cpu'):
        stock_price = stock_price.cpu().numpy()
    if hasattr(y_hat, 'cpu'):
        y_hat = y_hat.cpu().numpy()
    if hasattr(y_true, 'cpu'):
        y_true = y_true.cpu().numpy()
    if hasattr(p_hat, 'cpu'):
        p_hat = p_hat.cpu().numpy()
    
    N = len(stock_price)
    
    # Convert prediction_difficulty_scores if provided
    if prediction_difficulty_scores is not None and hasattr(prediction_difficulty_scores, 'cpu'):
        prediction_difficulty_scores = prediction_difficulty_scores.cpu().numpy()
    
    # Determine number of subplots based on prediction_difficulty_scores
    num_subplots = 8 if prediction_difficulty_scores is not None else 7
    
    # Create NxN figure
    fig, axes = plt.subplots(num_subplots, 1, figsize=(36, 16 if prediction_difficulty_scores is not None else 15), sharex=True)
    
    # 1. Stock price
    axes[0].plot(test_date_list, stock_price, color='black', linewidth=1)
    # set y-axis as log scale
    axes[0].set_yscale('log')
    axes[0].set_ylabel('Stock Price', fontsize=10)
    axes[0].set_title(f'{time_bar} Linear Trend, Issue ID: {issue_id}', fontsize=12, fontweight='bold')
    axes[0].grid(True, alpha=0.3)
    
    # 2-4. Probability predictions for each class
    class_labels = ['Class 0 (Down)', 'Class 1 (NoTouch)', 'Class 2 (Up)']
    colors = ['red', 'blue', 'green']
    
    ii = 0
    for i in range(2, -1, -1):  # Plot in reverse order so that Class 2 (Up) is on top
        axes[ii+1].plot(test_date_list, p_hat[:, i], color=colors[i], linewidth=1, alpha=0.7)
        axes[ii+1].set_ylabel(f'P({class_labels[i]})', fontsize=10)
        axes[ii+1].set_ylim([0, 1])
        axes[ii+1].axhline(y=0.33, color='black', linestyle='--', linewidth=0.5, alpha=0.3)
        axes[ii+1].grid(True, alpha=0.3)
        ii += 1
    
    # 5. Predicted labels (y_hat)
    axes[4].scatter(test_date_list, y_hat, color='red', s=10, alpha=0.6)
    axes[4].set_ylabel('Predicted Label', fontsize=10)
    axes[4].set_yticks([0, 1, 2])
    axes[4].set_ylim([-0.5, 2.5])
    axes[4].grid(True, alpha=0.3)
    
    # 6. True labels (y_true)
    axes[5].scatter(test_date_list, y_true, color='blue', s=10, alpha=0.6)
    axes[5].set_ylabel('True Label', fontsize=10)
    axes[5].set_yticks([0, 1, 2])
    axes[5].set_ylim([-0.5, 2.5])
    axes[5].grid(True, alpha=0.3)
    
    # 7. Prediction difficulty scores (if provided)
    if prediction_difficulty_scores is not None:
        axes[6].plot(test_date_list, prediction_difficulty_scores, color='purple', linewidth=1, alpha=0.7)
        axes[6].set_ylabel('Prediction Difficulty Score', fontsize=10)
        axes[6].set_ylim([0, 1])
        axes[6].axhline(y=0.33, color='black', linestyle='--', linewidth=0.5, alpha=0.3, label='Low/Med threshold')
        axes[6].axhline(y=0.67, color='black', linestyle='--', linewidth=0.5, alpha=0.3, label='Med/High threshold')
        axes[6].legend(loc='upper right', fontsize=9)
        axes[6].grid(True, alpha=0.3)
        overlay_idx = 7
    else:
        overlay_idx = 6
    
    # 8 (or 7). Overlay of predicted and true labels
    axes[overlay_idx].scatter(test_date_list, y_true, color='blue', s=10, alpha=0.6, label='True Labels')
    # Only plot predictions where they match truth (correct predictions)
    correct_mask = (y_hat == y_true)
    correct_dates = np.array(test_date_list)[correct_mask]
    correct_y_hat = y_hat[correct_mask]
    axes[overlay_idx].scatter(correct_dates, correct_y_hat, color='red', s=10, alpha=0.3, label='Correct Predictions')
    
    # Calculate and display accuracy
    accuracy = np.mean(correct_mask) * 100
    axes[overlay_idx].legend(title=f'Accuracy: {accuracy:.1f}%', loc='upper right', fontsize=9)
    
    axes[overlay_idx].set_ylabel('Label', fontsize=10)
    axes[overlay_idx].set_yticks([0, 1, 2])
    axes[overlay_idx].set_ylim([-0.5, 2.5])
    axes[overlay_idx].set_xlabel('Date', fontsize=10)
    axes[overlay_idx].grid(True, alpha=0.3)
    
    # Format x-axis to show dates nicely
    # Show every Nth date to avoid crowding
    step = max(1, N // 15)  # Show approximately 15 date labels
    xtick_positions = list(range(0, N, step))
    axes[overlay_idx].set_xticks([test_date_list[i] for i in xtick_positions])
    axes[overlay_idx].set_xticklabels([test_date_list[i] for i in xtick_positions], rotation=45, ha='right')
    
    plt.tight_layout()
    plt.savefig(wdir / f"predictions_over_time_{time_bar}_{lookback}_issueID_{issue_id}_LOG.png", dpi=300, bbox_inches='tight')
    plt.close()
    
def autocorrelation_of_predictions(y_hat_val, y_val, iid_list, test_date_list, wdir, lookback):
    """
    Plots the autocorrelation of predictions.
    """
    y_correct = (y_hat_val == y_val).int()

    # Convert to numpy
    y_correct_np = y_correct.cpu().numpy()  # shape (129469,)
    iid_list_np = np.array(iid_list)        # shape (129469,)

    # Group by issue_id
    unique_iids, inv_idx = np.unique(iid_list_np, return_inverse=True)
    MAXLAGS = 100  # or 100 if you want more
    
    # Compute ACF per stock (min 200 days, maxlags=100 or len//4)
    all_acfs = []
    valid_stocks = []
    for iid_idx in range(len(unique_iids)):
        mask = (inv_idx == iid_idx)
        series = y_correct_np[mask]
        if len(series) >= 100:
            acf_vals = sm.tsa.acf(series, nlags=MAXLAGS, fft=True)
            all_acfs.append(acf_vals)
            valid_stocks.append(unique_iids[iid_idx])

    all_acfs = np.array(all_acfs)
    avg_acf = np.mean(all_acfs, axis=0)
    print(f"ACF for {len(all_acfs)} stocks, avg lags 1-5: {avg_acf[1:6]}")

    # Effective sample size from average ACF
    M = 50  # truncate sum at lag 50 (reasonable for daily financial data)
    var_inflation = 1 + 2 * np.sum(avg_acf[1:M+1])
    total_raw_N = len(y_correct_np)  # 129469
    N_eff = total_raw_N / var_inflation

    print(f"Raw sample size: {total_raw_N:,}")
    print(f"Variance inflation: {var_inflation:.2f}")
    print(f"Effective sample size: {N_eff:,.0f}")
    print(f"N_eff / raw = {N_eff/total_raw_N:.1%}")
    
    
    p_hat = np.mean(y_correct_np)  # your observed accuracy, e.g. 0.70
    ci_low, ci_high = binom.interval(0.95, int(N_eff), p_hat)

    print(f"Observed accuracy: {p_hat:.1%}")
    print(f"95% CI with N_eff: [{ci_low/N_eff:.1%}, {ci_high/N_eff:.1%}]")
    print(f"95% CI with raw N:  [{binom.interval(0.95, total_raw_N, p_hat)[0]/total_raw_N:.1%}, "
        f"{binom.interval(0.95, total_raw_N, p_hat)[1]/total_raw_N:.1%}]")

    # 1. Report sparse accuracy as primary: "73.1% ±4.2% (N_eff=349)"
    # 2. Test different step sizes for trade-off
    for step in [60, 90, 180, 378]:
        sparse_acc = np.mean(y_correct_np[::step])
        print(f"Step {step}d: {sparse_acc:.1%} (N={len(y_correct_np)//step})")

    # 3. Block accuracy (monthly blocks)
    block_size = 21  # ~1 month trading days
    block_accs = []
    for i in range(0, len(y_correct_np)//block_size):
        block = y_correct_np[i*block_size:(i+1)*block_size]
        block_accs.append(np.mean(block))
    
    print(f"Block std: {np.std(block_accs):.1%} (vs raw std {np.std(y_correct_np):.1%})")
    print(f"Block mean accuracy: {np.mean(block_accs):.1%}")
    
    print("Block accuracies std:", np.std(block_accs))
    print("Worst month:", np.min(block_accs), "Best month:", np.max(block_accs))
    
    plt.figure(figsize=(10, 4))
    plot_acf(y_correct_np[mask], lags=MAXLAGS, title="Single IssueID: "+str(iid_idx))  # quick check
    plt.savefig(wdir / f"autocorrelation_of_predictions_issueID_{iid_idx}_{lookback}.png", dpi=300)
    
    plt.figure(figsize=(10, 4))
    lags = np.arange(len(avg_acf))
    plt.stem(lags, avg_acf)
    # plt.axhspan(-1.96/np.sqrt(730), 1.96/np.sqrt(730), alpha=0.2, color='blue')  # 95% bands
    plt.title("Average ACF across stocks")
    plt.savefig(wdir / f"autocorrelation_of_predictions_{lookback}.png", dpi=300)





    
def histogram_of_slope(slope_errors, slope_total, error_type, wdir, num_bins, lookback):
    """
    Plots a histogram of slope of errors and total slopes.
    """
    x_value = 1/lookback  # Assuming lookback is in days, e.g., 252 for a year
    
    plt.figure(figsize=(10, 6))

    # Compute bin edges
    bin_edges = np.linspace(-0.006, 0.006, num_bins+1)

    # Compute histograms
    error_counts, _ = np.histogram(slope_errors, bins=bin_edges)
    total_counts, _ = np.histogram(slope_total, bins=bin_edges)

    # Avoid division by zero
    ratio = np.divide(error_counts, total_counts, out=np.zeros_like(error_counts, dtype=float), where=total_counts!=0)

    # Plot histograms (stacked bars)
    plt.hist([slope_errors, slope_total],
             bins=bin_edges,
             label=[error_type, 'Total'],
             color=['salmon', 'skyblue'],
             histtype='bar',
             alpha=0.95)

    plt.axvline(x=x_value, color='black', linestyle='--', label=f'diagonal slope of 1/{lookback}')
    plt.axvline(x=-x_value, color='black', linestyle='--')  # If you want a line symmetric on the negative side

    plt.xlabel('Slope')
    plt.ylabel('Count')
    plt.yscale('log')
    plt.title(f'Histogram of {error_type} by Slope ({lookback}-day Model)')
    plt.grid(axis='y', linestyle='--', alpha=0.7)

    # Plot ratio as line with a second y-axis
    ax1 = plt.gca()
    ax2 = ax1.twinx()
    bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
    ax2.plot(bin_centers, ratio, color='black', marker='o', label=f'{error_type}/Total Ratio')
    ax2.set_ylabel(f'{error_type}/Total Ratio')
    ax2.set_ylim(0, 1)

    ax1.legend(loc='upper left')    # bar chart legend
    ax2.legend(loc='upper right')   # ratio line legend
    
    plt.tight_layout()
    plt.savefig(wdir / f"{error_type}_histogram_{lookback}_slopes.png", dpi=300)
    plt.close()

def histogram_of_ci_width(ci_widths_error, ci_widths_total, error_type, wdir, num_bins, lookback):
    """
    Plots a histogram of confidence interval widths plus the ratio of error to total counts in bins.
    """

    plt.figure(figsize=(10, 6))

    # Compute bin edges
    bin_edges = np.linspace(0, 1, num_bins+1)

    # Compute histograms
    error_counts, _ = np.histogram(ci_widths_error, bins=bin_edges)
    total_counts, _ = np.histogram(ci_widths_total, bins=bin_edges)

    # Avoid division by zero
    ratio = np.divide(error_counts, total_counts, out=np.zeros_like(error_counts, dtype=float), where=total_counts!=0)

    # Plot histograms (stacked bars)
    plt.hist([ci_widths_error, ci_widths_total],
             bins=bin_edges,
             label=[error_type, 'Total'],
             color=['salmon', 'skyblue'],
             histtype='bar',
             alpha=0.95)

    plt.xlabel('Confidence Interval Width')
    plt.ylabel('Count')
    plt.yscale('log')
    plt.title(f'Histogram of {error_type} by CI Width ({lookback}-day Model)')
    plt.grid(axis='y', linestyle='--', alpha=0.7)

    # Plot ratio as line with a second y-axis
    ax1 = plt.gca()
    ax2 = ax1.twinx()
    bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
    ax2.plot(bin_centers, ratio, color='black', marker='o', label=f'{error_type}/Total Ratio')
    ax2.set_ylabel(f'{error_type}/Total Ratio')
    ax2.set_ylim(0, 1)
    
    ax1.legend(loc='upper left')    # bar chart legend
    ax2.legend(loc='upper right')   # ratio line legend

    plt.tight_layout()
    plt.savefig(wdir / f"{error_type}_histogram_{lookback}_ci_widths.png", dpi=300)
    plt.close()

def histogram_of_issueId(unique_list, error_counts, total_counts, error_type, wdir, lookback):
    """ 
    Plots a histogram of issue ID.
    """
    plt.figure(figsize=(30, 6))
    x = np.arange(len(unique_list)) * 1.5 # positions for bars
    bar_width = 0.4

    plt.bar(x - bar_width/2, error_counts, width=bar_width, label=error_type, color='salmon')
    plt.bar(x + bar_width/2, total_counts, width=bar_width, label='Total', color='skyblue')

    plt.xlabel('Issue ID')
    plt.ylabel('Count')
    plt.title(f'Histogram of {error_type} by Issue ID ({lookback}-day Model)')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.xticks(x, unique_list, rotation=90)
    plt.legend()
    plt.tight_layout()
    plt.savefig(wdir / f"{error_type}_histogram_{lookback}_iids.png", dpi = 300)
    plt.close()

def histogram_of_sector(unique_list, error_counts, total_counts, error_type, wdir, lookback):
    """
    Plots a histogram of sector codes.
    """
    plt.figure(figsize=(8, 6))
    x = np.arange(len(unique_list))  # positions for bars
    bar_width = 0.4

    # Plot the grouped bar chart
    ax1 = plt.gca()
    ax1.bar(x - bar_width/2, error_counts, width=bar_width, label=error_type, color='salmon')
    ax1.bar(x + bar_width/2, total_counts, width=bar_width, label='Total', color='skyblue')

    plt.xlabel('Sector Code')
    ax1.set_ylabel('Count')
    plt.title(f'Histogram of {error_type} by Sector Code ({lookback}-day Model)')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.xticks(x, unique_list)

    # Compute and plot ratio line
    ratio = np.divide(error_counts, total_counts, out=np.zeros_like(error_counts, dtype=float), where=total_counts != 0)
    ax2 = ax1.twinx()
    ax2.plot(x, ratio, color='black', marker='o', linestyle='-', label=f'{error_type}/Total Ratio')
    ax2.set_ylabel(f'{error_type}/Total Ratio')
    ax2.set_ylim(0, 1)

    # Legends
    ax1.legend(loc='upper left')    # bar chart legend
    ax2.legend(loc='upper right')   # ratio line legend

    plt.tight_layout()
    plt.savefig(wdir / f"{error_type}_histogram_{lookback}_sectors.png")
    plt.close()

def histogram_of_year(unique_list, error_counts, total_counts, error_type, wdir, lookback):
    """
    Plots a histogram of year.
    """
    plt.figure(figsize=(8, 6))
    x = np.arange(len(unique_list))  # positions for bars
    bar_width = 0.4

    ax1 = plt.gca()
    ax1.bar(x - bar_width/2, error_counts, width=bar_width, label=error_type, color='salmon')
    ax1.bar(x + bar_width/2, total_counts, width=bar_width, label='Total', color='skyblue')

    plt.xlabel('Year')
    ax1.set_ylabel('Count')
    plt.title(f'Histogram of {error_type} by Year ({lookback}-day Model)')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.xticks(x, unique_list)  # Skip the first year if it's not relevant
    
     # Compute and plot ratio line
    ratio = np.divide(error_counts, total_counts, out=np.zeros_like(error_counts, dtype=float), where=total_counts != 0)
    ax2 = ax1.twinx()
    ax2.plot(x, ratio, color='black', marker='o', linestyle='-', label=f'{error_type}/Total Ratio')
    ax2.set_ylabel(f'{error_type}/Total Ratio')
    ax2.set_ylim(0, 1)
    
    # Legends
    ax1.legend(loc='upper left')    # bar chart legend
    ax2.legend(loc='upper right')   # ratio line legend
    
    plt.tight_layout()
    plt.savefig(wdir / f"{error_type}_histogram_{lookback}_years.png")
    plt.close()

def histogram_of_price(error_prices, total_prices, error_type, wdir, num_bins, lookback):
    """
    Plots a histogram of test prices.
    """

    plt.figure(figsize=(10, 6))

    # Compute bin edges
    bin_edges = np.linspace(-2, 2, num_bins + 1)

    # Get histogram counts
    error_counts, _ = np.histogram(error_prices, bins=bin_edges)
    total_counts, _ = np.histogram(total_prices, bins=bin_edges)

    # Calculate ratio, avoid division by zero
    ratio = np.divide(error_counts, total_counts, out=np.zeros_like(error_counts, dtype=float), where=total_counts != 0)
    bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2

    ax1 = plt.gca()

    # Plot histograms
    ax1.hist(
        [error_prices, total_prices],
        bins=bin_edges,
        label=[error_type, 'Total'],
        color=['salmon', 'skyblue'],
        histtype='bar',
        alpha=0.95
    )

    plt.xlabel('Deviation of Test price from mid-price (relative to CI width)')
    ax1.set_ylabel('Count')
    plt.yscale('log')
    plt.title(f'Histogram of {error_type} by deviation amount ({lookback}-day Model)')
    plt.grid(axis='y', linestyle='--', alpha=0.7)

    # Plot ratio: secondary y-axis
    ax2 = ax1.twinx()
    ax2.plot(bin_centers, ratio, color='black', marker='o', label=f'{error_type}/Total Ratio')
    ax2.set_ylabel(f'{error_type}/Total Ratio')
    ax2.set_ylim(0, 1)

    # Legends
    ax1.legend(loc='upper left')    # bar chart legend
    ax2.legend(loc='upper right')   # ratio line legend

    plt.tight_layout()
    plt.savefig(wdir / f"{error_type}_histogram_{lookback}_prices.png", dpi=300)
    plt.close()
    
def histogram_of_labels_vs_price(labels, test_prices, error_type, wdir, num_bins, lookback):
    """
    Plots a histogram of labels vs test price deviations.
    """
    # Define bins
    bin_edges = np.linspace(-2, 2, 51)  # 50 bins, edges from -2 to 2

    labels = labels.squeeze()
    # Separate data by label
    a = test_prices[labels == 0]
    b = test_prices[labels == 1]

    plt.figure(figsize=(10, 6))
    ax1 = plt.gca()

    ax1.hist(
        [a, b],
        bins=bin_edges,
        label=['Label 0', 'Label 1'],
        color=['salmon', 'skyblue'],
        histtype='bar',
        alpha=0.95
    )

    plt.xlabel("Deviation of Test price from mid-price (relative to CI width)")
    plt.ylabel("Count")
    plt.title(f"Histogram of labels by deviation amount ({lookback}-day Model)")
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.legend()
    plt.tight_layout()
    plt.savefig(wdir / f"histogram_{lookback}_labels_vs_price.png", dpi=300)
    plt.close()

def histogram_of_preds_vs_price(labels, test_prices, error_type, wdir, num_bins, lookback):
    """
    Plots a histogram of labels vs test price deviations.
    """
    # Define bins
    bin_edges = np.linspace(-2, 2, 51)  # 50 bins, edges from -2 to 2

    labels = labels.squeeze()
    # Separate data by label
    a = test_prices[labels == 0]
    b = test_prices[labels == 1]

    plt.figure(figsize=(10, 6))
    ax1 = plt.gca()

    ax1.hist(
        [a, b],
        bins=bin_edges,
        label=['Label 0', 'Label 1'],
        color=['salmon', 'skyblue'],
        histtype='bar',
        alpha=0.95
    )

    plt.xlabel("Deviation of Test price from mid-price (relative to CI width)")
    plt.ylabel("Count")
    plt.title(f"Histogram of predictions by deviation amount ({lookback}-day Model)")
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.legend()
    plt.tight_layout()
    plt.savefig(wdir / f"histogram_{lookback}_preds_vs_price.png", dpi=300)
    plt.close()

def heatmap_probs_vs_price(p_hat_val, test_price, wdir, lookback):
    with plt.rc_context({'font.size': 20}):
        p_hat_val = p_hat_val.squeeze().cpu().numpy()
        test_price = test_price.squeeze().cpu().numpy()

        # Define bin edges
        num_p_bins = 51
        num_price_bins = 51
        p_bins = np.linspace(0, 1, num_p_bins)
        price_bins = np.linspace(-2, 2, num_price_bins)

        # Compute 2D histogram
        heatmap, xedges, yedges = np.histogram2d(test_price, p_hat_val, bins=[price_bins, p_bins])

        # Calculate bin centers for tick labels
        price_centers = (xedges[:-1] + xedges[1:]) / 2
        p_centers = (yedges[:-1] + yedges[1:]) / 2

        plt.figure(figsize=(16, 12))
        ax = sns.heatmap(
            heatmap.T,
            cmap='viridis',
            cbar_kws={'label': 'Count'},
            xticklabels=10,  # show every 10th tick on x by default, override next
            yticklabels=10   # show every 10th tick on y by default, override next
        )

        # Create tick positions (indices) for x and y at reasonable intervals
        x_tick_indices = np.linspace(0, num_price_bins - 2, 9, dtype=int)  # 9 ticks across price axis
        x_tick_labels = [f"{price_centers[i]:.1f}" for i in x_tick_indices]
        plt.xticks(ticks=x_tick_indices + 0.5, labels=x_tick_labels)  # +0.5 to center labels on bins

        y_tick_indices = np.arange(0, num_p_bins - 1, 5)  # every 5 bins on p_hat axis
        y_tick_labels = [f"{p_centers[i]:.1f}" for i in y_tick_indices]
        plt.yticks(ticks=y_tick_indices + 0.5, labels=y_tick_labels, rotation=0)  # +0.5 centers labels

        plt.xlabel('Deviation of Test price from mid-price (relative to CI width)')
        plt.ylabel('Predicted Probability (p_hat)')
        plt.title('Heatmap of Predictions vs Deviation Amount')
        ax.invert_yaxis()  # match typical heatmap orientation

        plt.tight_layout()
        plt.savefig(wdir / f"heatmap_{lookback}_probs_vs_price.png", dpi=300)
        plt.close()

def prediction_count_over_time(test_date, y_hat_val, wdir, lookback):
    """
    Plots the count of positive and negative predictions over time.
    """
    y_hat_val = y_hat_val.squeeze().numpy()
    df = pd.DataFrame({'test_date': test_date, 'y_hat': y_hat_val})

    # Count positive and negative occurrences for each date
    grouped = df.groupby(['test_date', 'y_hat']).size().unstack(fill_value=0)
    grouped = grouped.rename(columns={0: 'negative', 1: 'positive'})  # Optional: rename for clarity

    # Plot grouped bar chart
    fig, ax = plt.subplots(figsize=(30, 6))

    width = 0.2  # width of each bar
    xticks = range(len(grouped))

    ax.bar([x - width/2 for x in xticks], grouped['positive'], width=width, label='Positive')
    ax.bar([x + width/2 for x in xticks], grouped['negative'], width=width, label='Negative')

    # Set x-tick positions to every 5th date
    xtick_positions = list(range(0, len(grouped), 5))
    ax.set_xticks(xtick_positions)
    ax.set_xticklabels([grouped.index[i] for i in xtick_positions], rotation=90)
    plt.xlabel('Test Date')
    plt.ylabel('Count')
    plt.title('Occurrences of Positive and Negative Predictions for Each Test Date')
    plt.legend()
    plt.tight_layout()
    plt.savefig(wdir / f"predictions_count_over_time_{lookback}.png", dpi=300)
    plt.close()

def issueID_over_time(test_date, y_hat_val, y_val, wdir, lookback, issueID):
    """
    Plots the predictions over time for a specific issue ID.
    """
    y_hat_val = y_hat_val.squeeze().numpy()
    y_val = y_val.squeeze().numpy()

    fig, ax = plt.subplots(figsize=(30, 6))
    ax.plot(test_date, y_hat_val, marker='o', linestyle='-', label='Predicted')
    ax.plot(test_date, y_val, marker='x', linestyle='--', label='Label')
    plt.xlabel('Test Date')
    plt.ylabel('Value')
    plt.title(f'Predictions Over Time for Issue ID: {issueID}')
    xtick_positions = list(range(0, len(test_date), 5))
    plt.xticks(xtick_positions, [test_date[i] for i in xtick_positions], rotation=90)
    plt.legend()
    plt.tight_layout()
    plt.savefig(wdir / f"predictions_over_time_{lookback}_issueID_{issueID}.png")
    plt.close()

def issueID_count_over_time(test_date, iid_val, wdir, lookback):
    """
    Plots the count of issue IDs over time.
    """
    df = pd.DataFrame({'test_date': test_date, 'issue_id': iid_val})

    # Count occurrences for each date
    counts = df.groupby('test_date').size()

    fig, ax = plt.subplots(figsize=(30, 6))
    counts.plot(kind='bar', ax=ax)
    plt.xlabel('Test Date')
    plt.ylabel('Count')
    plt.title('Number of distinct Issue IDs for Each Test Date')
    xtick_positions = list(range(0, len(counts), 5))
    ax.set_xticks(xtick_positions)
    ax.set_xticklabels([counts.index[i] for i in xtick_positions], rotation=90)
    plt.tight_layout()
    plt.savefig(wdir / f"issueID_over_time_{lookback}.png", dpi=300)
    plt.close()

def histogram_of_deviation_count(deviations, error_type, wdir, num_bins, lookback):
    """
    Plots a histogram of the count of deviations.
    """
    # Count the number of non-zero elements in each row of deviations
    non_zero_counts = (deviations != 0).sum(axis=1)

    # Get histogram counts and bin edges using np.histogram
    counts, bin_edges = np.histogram(non_zero_counts, bins=63)

    # Convert counts to percentage relative to total rows
    total_samples = non_zero_counts.shape[0]
    percentages = counts / total_samples * 100

    # Calculate bin centers for plotting
    bin_centers = 0.5 * (bin_edges[:-1] + bin_edges[1:])

    # Calculate the 95th percentile value
    percentile_95 = np.percentile(non_zero_counts, 95)
    
    plt.figure(figsize=(10, 6))
    plt.bar(bin_centers, percentages, width=(bin_edges[1] - bin_edges[0]), color='salmon', label=error_type)
    plt.axvline(percentile_95, color='green', linestyle='--', linewidth=2, label='95th Percentile')
    plt.text(percentile_95+1.5, 0.25, f"{percentile_95}", color='green', ha='center', va='top', fontsize=10)
    plt.title('Histogram of the number of days deviated from CI')
    plt.xlabel('Count of Deviations from CI (days)')
    plt.ylabel('Percentage (%)')
    plt.legend()
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.tight_layout()
    plt.savefig(wdir / f"deviation_count_histogram_{lookback}.png", dpi=300)
    plt.close()



def histogram_of_deviation(deviations, error_type, wdir, num_bins, lookback):
    """
    Plots a histogram of deviations.
    """
    all_deviations = deviations.squeeze().numpy().flatten()

    num_bins = 50
    counts, bin_edges = np.histogram(all_deviations, bins=num_bins, range=(-1, 1))
    total_samples = counts.sum()
    percentages = counts / total_samples * 100
    bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2

    # Calculate 2.5th and 97.5th percentiles to cover 95% of samples
    lower_bound = np.percentile(all_deviations, 2.5)
    upper_bound = np.percentile(all_deviations, 97.5)

    plt.figure(figsize=(10, 6))
    plt.bar(bin_centers, percentages, width=bin_edges[1] - bin_edges[0], color='salmon', label=error_type)

    # Plot vertical lines for 95% range
    plt.axvline(lower_bound, color='blue', linestyle='--', linewidth=2, label='2.5th Percentile')
    plt.axvline(upper_bound, color='green', linestyle='--', linewidth=2, label='97.5th Percentile')

    # Add text annotations for percentiles on x-axis, slightly below x-axis (y=0)
    plt.text(lower_bound+0.06, 0.00005, f"{lower_bound:.2f}", color='blue', ha='center', va='top', fontsize=10)
    plt.text(upper_bound+0.06, 0.00005, f"{upper_bound:.2f}", color='green', ha='center', va='top', fontsize=10)

    plt.title('Histogram of Deviations Amount')
    plt.xlabel('Deviation from CI (relative to mid-price)')
    plt.ylabel('Percentage (%)')
    plt.yscale('log')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.legend()

    # Formatter to show y-ticks as percentages without scientific notation
    def percent_formatter(y, _):
        # For log scale, some ticks might be too small or zero
        if y <= 0:
            return "0"
        return f"{y:.2f}"

    plt.gca().yaxis.set_major_formatter(FuncFormatter(percent_formatter))
    plt.tight_layout()
    plt.savefig(wdir / f"deviation_histogram_{lookback}.png", dpi=300)
    plt.close()


def heatmap_of_deviation(deviations, wdir, lookback):
    with plt.rc_context({'font.size': 20}):
        num_bins = 21
        bin_range = (-1, 1)  # adjust based on your deviation range

        hist_counts = np.zeros((num_bins, deviations.shape[1]))

        # Compute histograms
        for day in range(deviations.shape[1]):
            counts, _ = np.histogram(deviations[:, day], bins=num_bins, range=bin_range)
            hist_counts[:, day] = counts

        # Normalize counts per day to get percentage (relative frequency)
        samples_per_day = np.sum(hist_counts, axis=0, keepdims=True)  # shape: (1, number_of_days)
        hist_counts_pct = hist_counts / samples_per_day * 100  # shape: (num_bins, number_of_days)

        # Optionally, apply log transform for better contrast (use percentages directly if preferred)
        hist_counts_log = np.log1p(hist_counts_pct) # log-scale for visualization

        plt.figure(figsize=(20, 12))
        ax = sns.heatmap(hist_counts_pct, cmap='viridis',
                    cbar_kws={'label': 'Percentage (%)'},
                    xticklabels=10,
                    yticklabels=np.round(np.linspace(bin_range[0], bin_range[1], num_bins), 2))

        plt.title('Heatmap of Deviation Amount per Day')
        plt.xlabel('Day')
        plt.ylabel('Deviation from CI (relative to mid-price)')
        ax.invert_yaxis()
        plt.tight_layout()
        plt.savefig(wdir / f"deviation_heatmap_{lookback}.png", dpi=300)
        plt.close()


def plot_entropy_difficulty_overlay(entropy, prediction_difficulty_scores, test_date_list, issue_id, wdir, lookback, time_bar, num_classes=3):
    """
    Create a plot with entropy and difficulty overlaid on dual y-axes.
    
    Parameters:
    -----------
    entropy : array-like, shape (N,)
        Shannon entropy for each prediction
    prediction_difficulty_scores : array-like, shape (N,)
        Prediction difficulty scores for each prediction (from calculate_prediction_margin)
    test_date_list : list
        List of dates corresponding to predictions
    issue_id : str/int
        Stock identifier
    wdir : Path
        Working directory to save the plot
    lookback : int
        Lookback window size (for filename)
    time_bar : str
        Time bar specification
    num_classes : int, optional
        Number of classes (for max entropy calculation)
    """
    # Convert to numpy if needed
    if hasattr(entropy, 'cpu'):
        entropy = entropy.cpu().numpy()
    if hasattr(prediction_difficulty_scores, 'cpu'):
        prediction_difficulty_scores = prediction_difficulty_scores.cpu().numpy()
    
    N = len(entropy)
    
    # Create figure with entropy and difficulty on separate y-axes
    fig, ax1 = plt.subplots(figsize=(20, 6))
    
    # Plot entropy on left y-axis
    color = 'tab:blue'
    ax1.set_xlabel('Date', fontsize=12)
    ax1.set_ylabel('Entropy per Prediction', color=color, fontsize=12)
    line1 = ax1.plot(test_date_list, entropy, color=color, linewidth=2, label='Entropy', alpha=0.7)
    ax1.tick_params(axis='y', labelcolor=color)
    ax1.grid(True, alpha=0.3)
    
    # Add reference line for maximum entropy
    max_entropy = np.log(num_classes)
    ax1.axhline(y=max_entropy, color=color, linestyle='--', linewidth=1, alpha=0.3, label=f'Max Entropy ({max_entropy:.3f})')
    
    # Create second y-axis for difficulty
    ax2 = ax1.twinx()
    color = 'tab:orange'
    ax2.set_ylabel('Prediction Difficulty Score', color=color, fontsize=12)
    line2 = ax2.plot(test_date_list, prediction_difficulty_scores, color=color, linewidth=2, label='Difficulty Score', alpha=0.7)
    ax2.tick_params(axis='y', labelcolor=color)
    ax2.set_ylim([0, 1])
    
    # Add reference lines for difficulty thresholds
    ax2.axhline(y=0.33, color=color, linestyle='--', linewidth=1, alpha=0.3, label='Low/Med threshold (0.33)')
    ax2.axhline(y=0.67, color=color, linestyle='--', linewidth=1, alpha=0.3, label='Med/High threshold (0.67)')
    
    # Title
    title = f'{time_bar} - Entropy & Difficulty per Prediction, Issue ID: {issue_id}'
    ax1.set_title(title, fontsize=14, fontweight='bold')
    
    # Combine legends from both axes
    lines = line1 + line2
    labels = [l.get_label() for l in lines]
    ax1.legend(lines, labels, loc='upper left', fontsize=10)
    
    # Format x-axis
    step = max(1, N // 15)
    xtick_positions = list(range(0, N, step))
    ax1.set_xticks([test_date_list[i] for i in xtick_positions])
    ax1.set_xticklabels([test_date_list[i] for i in xtick_positions], rotation=45, ha='right')
    
    plt.tight_layout()
    plt.savefig(wdir / f"entropy_difficulty_overlay_{time_bar}_{lookback}_issueID_{issue_id}.png", dpi=300, bbox_inches='tight')
    plt.close()


def plot_entropy_difficulty_bins(entropy, prediction_difficulty_scores, issue_id, wdir, lookback, time_bar, num_classes=3, y_hat=None, y_true=None):
    """
    Create a 2D binned plot showing distribution of samples across entropy-difficulty categories.
    
    Parameters:
    -----------
    entropy : array-like, shape (N,)
        Shannon entropy for each prediction
    prediction_difficulty_scores : array-like, shape (N,)
        Prediction difficulty scores for each prediction
    issue_id : str/int
        Stock identifier
    wdir : Path
        Working directory to save the plot
    lookback : int
        Lookback window size (for filename)
    time_bar : str
        Time bar specification
    num_classes : int, optional
        Number of classes (for max entropy calculation)
    y_hat : array-like, optional
        Predicted labels (for accuracy per bin)
    y_true : array-like, optional
        True labels (for accuracy per bin)
    """
    # Convert to numpy if needed
    if hasattr(entropy, 'cpu'):
        entropy = entropy.cpu().numpy()
    if hasattr(prediction_difficulty_scores, 'cpu'):
        prediction_difficulty_scores = prediction_difficulty_scores.cpu().numpy()
    if y_hat is not None and hasattr(y_hat, 'cpu'):
        y_hat = y_hat.cpu().numpy()
    if y_true is not None and hasattr(y_true, 'cpu'):
        y_true = y_true.cpu().numpy()
    
    # Normalize entropy to [0, 1] range for easier binning
    max_entropy = np.log(num_classes)
    entropy_norm = entropy / max_entropy
    
    # Define bin edges (Low: 0-0.33, Medium: 0.33-0.67, High: 0.67-1.0)
    bin_edges = [0, 0.33, 0.67, 1.0]
    bin_labels = ['Low', 'Med', 'High']
    
    # Create 2D histogram
    entropy_bins = np.digitize(entropy_norm, bin_edges[:-1]) - 1
    difficulty_bins = np.digitize(prediction_difficulty_scores, bin_edges[:-1]) - 1
    
    # Clip to valid range (0, 1, 2)
    entropy_bins = np.clip(entropy_bins, 0, 2)
    difficulty_bins = np.clip(difficulty_bins, 0, 2)
    
    # Count samples in each bin
    counts = np.zeros((3, 3))
    accuracies = np.zeros((3, 3))
    
    for i in range(3):  # entropy bins
        for j in range(3):  # difficulty bins
            mask = (entropy_bins == i) & (difficulty_bins == j)
            counts[i, j] = mask.sum()
            
            # Calculate accuracy for this bin if labels provided
            if y_hat is not None and y_true is not None and mask.sum() > 0:
                accuracies[i, j] = (y_hat[mask] == y_true[mask]).mean() * 100
    
    # Create figure with two subplots
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))
    
    # Plot 1: Sample counts heatmap
    im1 = ax1.imshow(counts, cmap='YlOrRd', aspect='auto')
    ax1.set_xticks(np.arange(3))
    ax1.set_yticks(np.arange(3))
    ax1.set_xticklabels(bin_labels)
    ax1.set_yticklabels(bin_labels)
    ax1.set_xlabel('Prediction Difficulty Score', fontsize=12, fontweight='bold')
    ax1.set_ylabel('Entropy', fontsize=12, fontweight='bold')
    ax1.set_title('Sample Count Distribution', fontsize=14, fontweight='bold')
    
    # Add count annotations
    for i in range(3):
        for j in range(3):
            text = ax1.text(j, i, f'{int(counts[i, j])}',
                          ha="center", va="center", color="black", fontsize=12, fontweight='bold')
    
    # Add colorbar
    cbar1 = plt.colorbar(im1, ax=ax1)
    cbar1.set_label('Sample Count', fontsize=10)
    
    # Add interpretation labels in corners
    interpretations = {
        (0, 0): 'Ambiguous',        # Low entropy, Low difficulty
        (0, 2): 'Clear Winner',     # Low entropy, High difficulty
        (2, 0): 'Uncertain',        # High entropy, Low difficulty
        (2, 2): 'Uniform Classes',  # High entropy, High difficulty
    }
    
    for (i, j), label in interpretations.items():
        ax1.text(j, i, f'\n\n({label})', ha="center", va="center", 
                color="darkblue", fontsize=9, style='italic', alpha=0.7)
    
    # Plot 2: Accuracy heatmap (if labels provided)
    if y_hat is not None and y_true is not None:
        im2 = ax2.imshow(accuracies, cmap='RdYlGn', aspect='auto', vmin=0, vmax=100)
        ax2.set_xticks(np.arange(3))
        ax2.set_yticks(np.arange(3))
        ax2.set_xticklabels(bin_labels)
        ax2.set_yticklabels(bin_labels)
        ax2.set_xlabel('Prediction Difficulty Score', fontsize=12, fontweight='bold')
        ax2.set_ylabel('Entropy', fontsize=12, fontweight='bold')
        ax2.set_title('Accuracy per Bin (%)', fontsize=14, fontweight='bold')
        
        # Add accuracy annotations
        for i in range(3):
            for j in range(3):
                if counts[i, j] > 0:
                    text = ax2.text(j, i, f'{accuracies[i, j]:.1f}%',
                                  ha="center", va="center", color="black", fontsize=12, fontweight='bold')
                else:
                    text = ax2.text(j, i, 'N/A',
                                  ha="center", va="center", color="gray", fontsize=10)
        
        # Add colorbar
        cbar2 = plt.colorbar(im2, ax=ax2)
        cbar2.set_label('Accuracy (%)', fontsize=10)
    else:
        ax2.axis('off')
        ax2.text(0.5, 0.5, 'Accuracy calculation\nrequires labels', 
                ha='center', va='center', fontsize=14, color='gray')
    
    plt.suptitle(f'{time_bar} - Entropy vs Difficulty Distribution, Issue ID: {issue_id}', 
                fontsize=16, fontweight='bold', y=1.02)
    
    plt.tight_layout()
    plt.savefig(wdir / f"entropy_difficulty_bins_{time_bar}_{lookback}_issueID_{issue_id}.png", dpi=300, bbox_inches='tight')
    plt.close()


def plot_entropy_calibration_curve(entropy, prediction_difficulty_scores, issue_id, wdir, lookback=252, time_bar="daily"):
    """
    Plot binned calibration curve showing average entropy per difficulty bucket.
    
    This reveals whether entropy is well-calibrated with prediction difficulty:
    - Well-calibrated: entropy increases monotonically with difficulty
    - Poorly-calibrated: entropy doesn't correlate with difficulty
    
    Parameters:
    -----------
    entropy : array-like, shape (N,)
        Shannon entropy per prediction
    prediction_difficulty_scores : array-like, shape (N,)
        Prediction difficulty scores in [0, 1]
    issue_id : str
        Security identifier for plot title
    wdir : Path
        Working directory to save plot
    lookback : int
        Lookback period for plot naming
    time_bar : str
        Time bar type for plot naming
    """
    # Early return if no difficulty scores provided
    if prediction_difficulty_scores is None:
        print("Warning: prediction_difficulty_scores is None. Skipping entropy calibration curve.")
        return
    
    # Convert to numpy if needed
    if hasattr(entropy, 'cpu'):
        entropy = entropy.cpu().numpy()
    if hasattr(prediction_difficulty_scores, 'cpu'):
        prediction_difficulty_scores = prediction_difficulty_scores.cpu().numpy()
    
    n_bins = 10
    bin_edges = np.linspace(0, 1, n_bins + 1)
    bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
    
    # Compute average entropy per difficulty bin
    avg_entropy_per_bin = []
    counts_per_bin = []
    
    for i in range(n_bins):
        mask = (prediction_difficulty_scores >= bin_edges[i]) & (prediction_difficulty_scores < bin_edges[i+1])
        if mask.sum() > 0:
            avg_entropy_per_bin.append(entropy[mask].mean())
            counts_per_bin.append(mask.sum())
        else:
            avg_entropy_per_bin.append(np.nan)
            counts_per_bin.append(0)
    
    avg_entropy_per_bin = np.array(avg_entropy_per_bin)
    counts_per_bin = np.array(counts_per_bin)
    
    # Create calibration curve plot
    fig, ax = plt.subplots(figsize=(10, 6))
    
    # Plot entropy vs difficulty
    ax.plot(bin_centers, avg_entropy_per_bin, 'o-', linewidth=2.5, markersize=8, 
            color='#1f77b4', label='Average Entropy')
    
    # Add count annotations
    for i, (center, entropy_val, count) in enumerate(zip(bin_centers, avg_entropy_per_bin, counts_per_bin)):
        if count > 0:
            ax.annotate(f'n={int(count)}', xy=(center, entropy_val), 
                       xytext=(0, 8), textcoords='offset points', 
                       ha='center', fontsize=8, color='gray')
    
    ax.set_xlabel('Prediction Difficulty Score', fontsize=12, fontweight='bold')
    ax.set_ylabel('Average Shannon Entropy', fontsize=12, fontweight='bold')
    ax.set_title(f'Entropy Calibration Curve - {issue_id} (lookback={lookback})', 
                fontsize=13, fontweight='bold')
    ax.grid(True, alpha=0.3)
    ax.legend(fontsize=11)
    ax.set_xlim(-0.05, 1.05)
    ax.set_ylim(bottom=0)
    
    plt.tight_layout()
    
    # Save plot
    plot_filename = wdir / f"entropy_calibration_{issue_id}_{time_bar}_{lookback}.png"
    plt.savefig(plot_filename, dpi=150, bbox_inches='tight')
    plt.close()

